export const DEFAULT_FIELD_OFFSETS_PAGE_1: Record<string, { x: number; y: number }> = {
  auftrag_nr: { x: 14, y: 26 },
  bohrmeister: { x: 14, y: 26 },
  blatt_nr: { x: 20, y: 26 },
  projekt_name: { x: 20, y: 25 },
  bohrung_nr: { x: 0, y: 25 },
  durchfuehrungszeit: { x: 0, y: 20 },
  grundwasserstand: { x: 0, y: 15 },
  datum: { x: 0, y: 15 },
  uhrzeit: { x: 0, y: 15 },
  tiefe_m: { x: 10, y: 15 },
  uk_verrohrg: { x: 10, y: 15 },
  bohrtiefe: { x: 20, y: 15 },
  pegel_durchmesser: { x: 5, y: 10 },
  rok: { x: 5, y: 10 },
  passavant: { x: 0, y: 10 },
  ferngas: { x: 0, y: 10 },
  seba: { x: 0, y: 10 },
  sumpf: { x: 5, y: 7 },
  filter_rohr: { x: 10, y: 7 },
  sw: { x: 18, y: 7 },
  vollrohr_pvc: { x: 23, y: 7 },
  vollrohr_stahl: { x: 34, y: 7 },
  filterkies_von: { x: 5, y: 5 },
  filterkies_bis: { x: 5, y: 5 },
  tondichtung_von: { x: 20, y: 7 },
  tondichtung_bis: { x: 23, y: 7 },
  gegenfilter_von: { x: 0, y: 5 },
  gegenfilter_bis: { x: 3, y: 5 },
  tondichtung_von_2: { x: 20, y: 5 },
  tondichtung_bis_2: { x: 23, y: 5 },
  zement_bent_von: { x: 40, y: 5 },
  zement_bent_bis: { x: 43, y: 5 },
  bohrgut_von: { x: 40, y: 5 },
  bohrgut_bis: { x: 43, y: 5 },
  probe_gp: { x: 10, y: -27 },
  probe_kp: { x: -25, y: -25 },
  probe_sp: { x: -10, y: -25 },
  probe_wp: { x: 0, y: -25 },
  probe_ki: { x: 0, y: -25 },
  probe_bkb: { x: 0, y: -25 },
  probe_spt: { x: 0, y: -25 },
  uebergeben_am: { x: 10, y: -30 },
  uebergeben_an: { x: 10, y: -30 },
  schicht_a1: { x: 5, y: -5 },
  schicht_a2: { x: 0, y: -10 },
};

export const DEFAULT_ROW_FIELD_OFFSETS_PAGE_1: Record<
  string,
  Record<string, { x: number; y: number }>
> = {
  "0": {
    schicht_ansatzpunkt_bis: { x: 0, y: 0 },
    schicht_a1: { x: 3, y: 0 },
    schicht_a2: { x: 0, y: 0 },
    schicht_b: { x: 10, y: -7 },
    schicht_c: { x: 10, y: -7 },
    schicht_d: { x: 10, y: -7 },
    schicht_e: { x: 15, y: -7 },
    schicht_f: { x: 6, y: -7 },
    schicht_g: { x: 7, y: -7 },
    schicht_h: { x: 10, y: -7 },
    feststellungen: { x: 10, y: 0 },
    proben_art: { x: 20, y: 0 },
    proben_nr: { x: 20, y: 0 },
    proben_tiefe: { x: 20, y: -5 },
  },
  "1": {
    schicht_ansatzpunkt_bis: { x: 0, y: 0 },
    schicht_a1: { x: 0, y: 0 },
    schicht_a2: { x: 3, y: 0 },
    schicht_b: { x: 5, y: -7 },
    schicht_c: { x: 5, y: -7 },
    schicht_d: { x: 10, y: -10 },
    schicht_e: { x: 15, y: -12 },
    schicht_f: { x: 10, y: -10 },
    schicht_g: { x: 10, y: -10 },
    schicht_h: { x: 10, y: -10 },
    feststellungen: { x: 10, y: -10 },
    proben_art: { x: 20, y: -10 },
    proben_nr: { x: 20, y: -10 },
    proben_tiefe: { x: 20, y: -10 },
  },
  "2": {
    schicht_ansatzpunkt_bis: { x: 0, y: -10 },
    schicht_a1: { x: 0, y: -5 },
    schicht_a2: { x: 0, y: -5 },
    schicht_b: { x: 5, y: -20 },
    schicht_c: { x: 5, y: -15 },
    schicht_d: { x: 10, y: -15 },
    schicht_e: { x: 15, y: -20 },
    schicht_f: { x: 10, y: -20 },
    schicht_g: { x: 10, y: -20 },
    schicht_h: { x: 10, y: -20 },
    feststellungen: { x: 10, y: -10 },
    proben_art: { x: 20, y: -10 },
    proben_nr: { x: 20, y: -10 },
    proben_tiefe: { x: 20, y: -15 },
  },
  "3": {
    schicht_ansatzpunkt_bis: { x: 0, y: -10 },
    schicht_a1: { x: 0, y: -10 },
    schicht_a2: { x: 10, y: -10 },
    schicht_b: { x: 5, y: -20 },
    schicht_c: { x: 5, y: -20 },
    schicht_d: { x: 10, y: -20 },
    schicht_e: { x: 15, y: -23 },
    schicht_f: { x: 5, y: -20 },
    schicht_g: { x: 5, y: -20 },
    schicht_h: { x: 10, y: -25 },
    feststellungen: { x: 10, y: -20 },
    proben_art: { x: 20, y: -20 },
    proben_nr: { x: 20, y: -20 },
    proben_tiefe: { x: 20, y: -20 },
  },
};
